src/java/ch/bfh/jass/model/FinishedGame.java
package ch.bfh.jass.model;

import java.util.HashMap;
import java.util.Map;

/**
 * @author David Baumgartner <baumd9@bfh.ch>, Fabian Schneider <schnf6@bfh.ch>
 * @version 1.0
 */
public class FinishedGame {

    /**
     * The unique id of the game
     */
    private int gameID;
    /**
     * The user this game is according to.
     */
    private User user;
    /**
     * The team id of the user
     *
     */
    private int teamID;
    /**
     * The teams in this game.
     */
    private Map<Integer, Team> teams = new HashMap<Integer, Team>();

    /**
     * Class Constructor
     *
     * @param gameID
     * @param user
     */
    public FinishedGame(int gameID, User user) {
        this.gameID = gameID;
        this.user = user;
    }

    /**
     * Adds a player to the game.
     *
     * @param userToAdd
     * @param teamID
     */
    public void addPlayer(HistoryPlayer userToAdd, int teamID) {

        if (this.user.getUserID() == userToAdd.getUserID()) {
            this.teamID = teamID;
        }

        if (this.teams.containsKey(teamID)) {
            this.teams.get(teamID).addPlayer(userToAdd);
        } else {
            Team team = new Team(teamID);
            team.addPlayer(userToAdd);
            this.teams.put(teamID, team);
        }
    }
    
    /**
     * Returns the teams of the game. The game of the requestet user is on the
     * index 0.
     * @return 
     */
    public Team[] getTeams() {

        Team[] teamArray = new Team[this.teams.size()];
        teamArray[0] = this.teams.get(this.teamID);

        int i = 1;
        for (int teamid : this.teams.keySet()) {
            if (teamid != this.teamID && i < this.teams.size()) {
                teamArray[i] = this.teams.get(teamid);
                i++;
            }
        }
        return teamArray;
    }
    /**
     * Verifies if the requested user's team has won the game.
     * @return 
     */
    public boolean isHasWon() {
        Team[] teamArray = this.getTeams();
        for (int i = 1; i < teamArray.length; i++) {
            if (teamArray[0].getTeamPoints() < teamArray[i].getTeamPoints()) {
                return false;
            }
        }
        return true;
    }
}

src/java/ch/bfh/jass/model/Team.java
package ch.bfh.jass.model;

import java.util.ArrayList;
import java.util.List;

/**
 * @author David Baumgartner <baumd9@bfh.ch>, Fabian Schneider <schnf6@bfh.ch>
 * @version 1.0
 */
public class Team {

    /**
     * The unique id of the game
     */
    private int teamID;
    /**
     * The players in this game
     */
    private List<HistoryPlayer> players = new ArrayList<HistoryPlayer>();

    /**
     * Class Constructor
     *
     * @param teamID
     */
    public Team(int teamID) {
        this.teamID = teamID;
    }

    /**
     * Adds a player to the team.
     *
     * @param user
     */
    public void addPlayer(HistoryPlayer user) {
        if (!this.players.contains(user)) {
            this.players.add(user);
        }
    }

    /**
     * Returns the players of the team.
     *
     * @return
     */
    public String getTeamPlayers() {
        String playersString = "";
        for (HistoryPlayer user : this.players) {
            if (user.equals(this.players.get(0))) {
                playersString = user.getUsername();
            } else {
                playersString = playersString + " & " + user.getUsername();
            }
        }
        return playersString;
    }

    /**
     * Returns the points of the team.
     *
     * @return
     */
    public int getTeamPoints() {
        int points = 0;
        for (HistoryPlayer user : this.players) {
            points += user.getPoints();
        }
        return points;
    }

    /**
     * Returns the id of the team.
     *
     * @return
     */
    public int getTeamID() {
        return this.teamID;
    }
}

src/java/ch/bfh/jass/controller/GameBean.java
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package ch.bfh.jass.controller;

import ch.bfh.jass.exceptions.*;
import ch.bfh.jass.game.Card;
import ch.bfh.jass.game.Game;
import ch.bfh.jass.game.JassCardSet;
import ch.bfh.jass.game.Player;
import ch.bfh.jass.interfaces.IPlayer;
import ch.bfh.jass.model.EntityManager;
import ch.bfh.jass.model.FinishedGame;
import ch.bfh.jass.model.MessageFactory;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ActionEvent;
import javax.faces.event.AjaxBehaviorEvent;

/**
 * @author David Baumgartner <baumd9@bfh.ch>, Fabian Schneider <schnf6@bfh.ch>
 * @version 1.0
 */
@SessionScoped
@ManagedBean
public class GameBean implements Serializable {
    
    /**
     * The player object of the session
     */
    @ManagedProperty(value = "#{mainBean.player}")
    private IPlayer player = new Player();
    /**
     * EntityManager singleton
     */
    @ManagedProperty(value = "#{mainBean.entityManager}")
    private EntityManager entityManager;
    /**
     * The game in which the player is
     */
    private Game game;
    /**
     * Is the player on a place in the game
     */
    private boolean hasPlace = false;
    /**
     * Is the player game administrator of the game
     */
    private boolean gameAdmin = false;

    /**
     * Set the player
     * @param player
     */
    public void setPlayer(IPlayer player) {
        this.player = player;
    }

    /**
     * @return true if the game is started
     */
    public boolean isStarted() {
        if (this.game != null) {
            return this.game.isStarted();
        }
        return false;
    }

    /**
     * @return the handcards of the player
     */
    public List<Card> getPlayerCards() {
        return this.player.getHandCards();
    }

    /**
     * @return a list of all games which you can join
     */
    public Game[] getGameOverview() {
        List<Game> games = new ArrayList<Game>(this.entityManager.getGames().values());
        List<Game> newGames = new ArrayList<Game>();
        Collections.reverse(games);

        for (Game game_a : games) {
            if (game_a.getPlayerCount() < 4) {
                newGames.add(game_a);
            }
        }
        Game[] gameOverview = new Game[newGames.size()];
        return newGames.toArray(gameOverview);
    }

    /**
     * Join a game
     * @param e ActionEvent
     */
    public void join(ActionEvent e) {
        try {
            this.game = this.entityManager.getGameByID(e.getComponent().getAttributes().get("title").toString());
        } catch (GameNotExistsException ex) {
            MessageFactory.error("gameDoesNotExist");
        }
    }

    /**
     * Create a new game in which you are administrator
     * @return
     */
    public String newGame() {
        if (this.game != null) {
            MessageFactory.error("alreadyInAGame");
        } else {
            try {
                this.game = new Game(this.player);
                this.entityManager.addGame(this.game);
                this.hasPlace = true;
                this.gameAdmin = true;
            } catch (PlayerAlreadyInGameException ex) {
                MessageFactory.error("playerAlreadyInGame");
            } catch (PlaceTakenException ex) {
                MessageFactory.error("placeTaken");
            } catch (PlaceDoesNotExistException ex) {
                MessageFactory.error("placeDoesNotExist");
            }
        }
        return "game";
    }

    /**
     * Start the game
     * @return
     */
    public String start() {
        try {
            this.game.start(player);
        } catch (YouMustNotException ex) {
            MessageFactory.error("mustNotStartGame");
        }
        this.playAI();
        return "game";
    }

    /**
     * Leave the game
     * @return
     */
    public String leave() {
        this.finishGame(this.game);
        this.game = null;
        this.gameAdmin = false;
        this.hasPlace = false;
        this.player.clearHand();
        this.player.setPlace(0);
        return "game";
    }

    /**
     * Listener for card clicks, plays the card which was clicked
     * @param event
     */
    public void cardClickListener(AjaxBehaviorEvent event) {
        try {
            String cardID = event.getComponent().getId();
            String[] card = cardID.split("_");
            this.game.play(new Card(JassCardSet.CardColor.valueOf(card[0]), JassCardSet.CardRank.valueOf(card[1])));
            this.playAI();
        } catch (NotYourCardException ex) {
            MessageFactory.error("notYourTurn");
        } catch (IsNotPlayableException ex) {
            MessageFactory.error("cardNotPlayable");
        } catch (GameOverException ex) {
            this.finishGame(this.game);
        } catch (NoTrumpfSetException ex) {
            MessageFactory.error("noTrumpfSet");
        }
    }

    /**
     * Listener for clicks on the place you want join, takes the place if it's free
     * @param event
     */
    public void placeClickListener(AjaxBehaviorEvent event) {
        try {
            String placeID = event.getComponent().getId();
            String[] place = placeID.split("_");
            this.game.addPlayer(this.player, Integer.parseInt(place[1]));
            this.hasPlace = true;
        } catch (PlayerAlreadyInGameException ex) {
            MessageFactory.error("playerAlreadyInGame");
        } catch (PlaceTakenException ex) {
            MessageFactory.error("placeTaken");
        } catch (PlaceDoesNotExistException ex) {
            MessageFactory.error("placeDoesNotExist");
        }
    }

    /**
     * Set the entityManager
     * @param entityManager
     */
    public void setEntityManager(EntityManager entityManager) {
        this.entityManager = entityManager;
    }

    /**
     * @return the trump of the game as a string
     */
    public String getTrumpf() {
        if (this.game == null || this.game.getTrumpf() == null) {
            return MessageFactory.getText("gameNoTrumpf");
        } else {
            return this.game.getTrumpf().toString();
        }
    }

    /**
     * Listener for trump choose, sets the trump for the new round
     * @param event
     */
    public void trumpfClickListener(AjaxBehaviorEvent event) {
        try {
            this.game.setTrumpf(JassCardSet.CardColor.valueOf(event.getComponent().getId()), this.player);
        } catch (YouMustNotSetTrumpfException ex) {
            MessageFactory.error("mustNotSetTrumpf");
        }
    }

    /**
     * @return true if you have the permission to set the trump
     */
    public boolean getCanSetTrumpf() {
        if (this.game != null && this.game.isStarted()) {
            if (this.game.getTrumpf() == null) {

                if (!this.game.isTrumpfMoved()) {
                    if (this.game.getCurrentPlayer().equals(this.player)) {
                        return true;
                    }
                } else {
                    if (this.game.getCurrentPlayer().equals(this.game.getTeamPlayer(this.player))) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    /**
     * Moves the permission to set the trump to your teammate
     * @return
     */
    public String moveTrumpf() {
        if (this.getCanSetTrumpf() && !this.game.isTrumpfMoved()) {
            try {
                this.game.moveTrumpf();
            } catch (YouMustNotSetTrumpfException ex) {
                MessageFactory.error("mustNotSetTrumpf");
            }
        }
        return "game";
    }

    /**
     * @return true if the trump set permission is moved to the teammate
     */
    public boolean isTrumpfMoved() {
        return this.game.isTrumpfMoved();
    }

    /**
     * @return a list of the cards which are on the table
     */
    public Card[] getTable() {
        if (this.game == null) {
            return new Card[0];
        }
        Card[] cards = this.game.getTable().getTableCardsArray();
        Card[] newCards = new Card[cards.length];
        int place = this.player.getPlace();

        for (int i = 0; i < cards.length; i++) {
            newCards[i] = cards[place];
            place++;
            if (place >= cards.length) {
                place = 0;
            }
        }
        return newCards;
    }

    /**
     * @return an array of the players which are in the game, array is rotated so that you are on position 0
     */
    public IPlayer[] getPlayers() {
        if (this.game == null) {
            return new IPlayer[0];
        }
        List<IPlayer> players = this.game.getPlayers();

        IPlayer[] newPlayers = new IPlayer[players.size()];
        int place = this.player.getPlace();

        for (int i = 0; i < players.size(); i++) {
            newPlayers[i] = players.get(place);
            place++;
            if (place >= players.size()) {
                place = 0;
            }
        }
        return newPlayers;
    }

    /**
     * trigger the AIPlayer that he plays a card or chooses the trump
     */
    public void playAI() {
        try {
            if (this.game.getCurrentPlayer().isAI() && !this.game.hasWinner()) {
                this.game.playAI();
                this.playAI();
            }
        } catch (GameOverException ex) {
            this.finishGame(this.game);
        }
    }

    /**
     * @return a list with arrays of the team points of each round
     */
    public List<int[]> getTeamPoints() {
        if (this.game == null) {
            return new ArrayList<int[]>();
        }
        return this.game.getTeamPoints();
    }
    
    /**

web/game.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"     
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:t="http://myfaces.apache.org/tomahawk">
    <h:head>
    </h:head>
    <h:body>
        <ui:composition template="template.xhtml">
            <ui:define name="content">
                <t:div rendered="#{empty gameBean.game}">
                    <ui:include src="gameoverview.xhtml"/>
                </t:div>
                <t:div rendered="#{not empty gameBean.game}">
                    <ui:include src="gameTable.xhtml"/>
                    <script type="text/javascript">
                        startAjaxPoll();
                    </script>
                </t:div>
                <t:div rendered="#{empty gameBean.game or gameBean.hasWinner}">
                    <script type="text/javascript">
                        stopAjaxPoll();
                    </script>
                </t:div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/gameTable.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"     
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:t="http://myfaces.apache.org/tomahawk">
    <h:head>
    </h:head>
    <h:body>
        <ui:composition xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:t="http://myfaces.apache.org/tomahawk" xmlns:fn="http://java.sun.com/jsp/jstl/functions">
            <h:outputScript name="jsf.js" library="javax.faces" target="head"/>
            <h:outputScript name="jassPolling.js" library="script" target="head"/>

            <div id="logo" class="logo_game">
                Jass
            </div>
            <div id="game">
                <div id="controlls">
                    <t:div id="gamecontrols">
                        <h:commandButton id="startBtn" action="#{gameBean.start}" value="#{text.gameStartButton}" rendered="#{not gameBean.started and gameBean.gameAdmin}" class="button green">
                            <f:ajax event="action" render="@form" execute="@this"/>
                        </h:commandButton>
                        <f:ajax event="click" render="@form" execute="@this" listener="#{gameBean.trumpfClickListener}">
                            <div id="chooseTrump">
                                <t:div rendered="#{gameBean.canSetTrumpf}">#{text.chooseTrump}</t:div>
                            </div>
                            <p><h:commandLink id="HERZ" value="HERZ" rendered="#{gameBean.canSetTrumpf}" class="button small red"/></p>
                            <p><h:commandLink id="ECKE" value="ECKE" rendered="#{gameBean.canSetTrumpf}" class="button small red"/></p>
                            <p><h:commandLink id="SCHAUFEL" value="SCHAUFEL" rendered="#{gameBean.canSetTrumpf}" class="button small"/></p>
                            <p><h:commandLink id="KREUZ" value="KREUZ" rendered="#{gameBean.canSetTrumpf}" class="button small"/></p>
                        </f:ajax>
                        <h:commandButton id="moveTrumpBtn" action="#{gameBean.moveTrumpf()}" value="#{text.gameMoveTrumpButton}" rendered="#{gameBean.canSetTrumpf and not gameBean.trumpfMoved}" class="button green moveTrump">
                            <f:ajax event="action" render="@form" execute="@this"/>
                        </h:commandButton>
                        <f:ajax event="click" render="@form" execute="@this" listener="#{gameBean.placeClickListener}">
                            <div id="place0">
                                <h:commandLink id="place_0" class="button blue" value="Enter" rendered="#{not gameBean.hasPlace}"/>
                            </div>
                            <div id="place1">
                                <h:commandLink id="place_1" class="button blue" value="Enter" rendered="#{not gameBean.hasPlace}"/>
                            </div>
                            <div id="place2">
                                <h:commandLink id="place_2" class="button blue" value="Enter" rendered="#{not gameBean.hasPlace}"/>
                            </div>
                            <div id="place3">
                                <h:commandLink id="place_3" class="button blue" value="Enter" rendered="#{not gameBean.hasPlace}"/>
                            </div>
                        </f:ajax>
                    </t:div>
                </div>
                <div id="infos">
                    <div id="turn">
                        <t:div id="nextTurn">
                            <t:div id="turn" styleClass="button small nolink" rendered="#{not gameBean.hasWinner and gameBean.started}">#{gameBean.currentUsername}#{text.gameTurn}</t:div>     
                        </t:div>
                    </div>
                    <t:div id="trump">
                        <p id="trumpf" class="radius #{fn:toLowerCase(gameBean.trumpf)}">#{text.gameTrumpf}</p>
                    </t:div>
                    <t:div id="finishMessage">
                        <h:outputText value="#{gameBean.winnerMessage}" class="button message  nolink" rendered="#{gameBean.hasWinner}"/>
                    </t:div>
                    <h:messages id="globalMessage" class="button message red nolink" globalOnly="true"/>

                </div>
                <div id="results_button" class="radius">
                    <div class="radius">
                        <span>
                            #{text.points}
                        </span>
                    </div>
                </div>
                <t:div id="results">
                    <div id="results" class="radius">
                        <div class="radius">
                            <p class="left teamA result_header">#{text.gameTeam} A</p>
                            <p class="left teamB result_header">#{text.gameTeam} B</p>
                            <c:forEach var="points" items="#{gameBean.teamPoints}">
                                <p class="left teamA">#{points[0]} #{text.points}</p>
                                <p class="left teamB">#{points[1]} #{text.points}</p>
                            </c:forEach>
                        </div>
                    </div>
                </t:div>
                <t:div id="gametable">
                    <div id="player3" class="player opponent">
                        <t:div rendered="#{gameBean.players[2].username != null}">
                            <div class="username" id="username_3">
                                <div class="button nolink">
                                    #{gameBean.players[2].username}
                                </div>
                            </div>
                        </t:div>
                        <ul class="cards">
                            <c:forEach var="card" items="#{gameBean.players[2].handCards}">
                                <li class="card left radius coverd"></li>
                            </c:forEach>
                        </ul>
                    </div>
                    <div id="player4" class="player opponent left">
                        <t:div rendered="#{gameBean.players[3].username != null}">
                            <div class="username" id="username_4">
                                <div class="button nolink">
                                    #{gameBean.players[3].username}
                                </div>
                            </div>
                        </t:div>
                        <ul class="cards">
                            <c:forEach var="card" items="#{gameBean.players[3].handCards}">
                                <li class="card left radius coverd"></li>
                            </c:forEach>
                        </ul>
                    </div>

                    <div id="table">
                        <ul id="cardcontainers">
                            <li id="table_top">
                                <div class="card radius position1 #{fn:toLowerCase(gameBean.table[2].color)}_#{fn:toLowerCase(gameBean.table[2].rank)}"></div>
                            </li>
                            <li id="table_left">
                                <div class="card radius rotate position2 #{fn:toLowerCase(gameBean.table[3].color)}_#{fn:toLowerCase(gameBean.table[3].rank)}"></div>
                            </li>
                            <li id="table_right">
                                <div class="card radius rotate position4 #{fn:toLowerCase(gameBean.table[1].color)}_#{fn:toLowerCase(gameBean.table[1].rank)}"></div>
                            </li>
                            <li id="table_bottom">
                                <div class="card radius position3 #{fn:toLowerCase(gameBean.table[0].color)}_#{fn:toLowerCase(gameBean.table[0].rank)}"></div>
                            </li>
                        </ul>
                    </div>
                    <div id="player2" class="player opponent left">
                        <t:div rendered="#{gameBean.players[1].username != null}">
                            <div class="username" id="username_2">
                                <div class="button nolink">
                                    #{gameBean.players[1].username}
                                </div>
                            </div>
                        </t:div>
                        <ul class="cards">
                            <c:forEach var="card" items="#{gameBean.players[1].handCards}">
                                <li class="card left radius coverd"></li>
                            </c:forEach>
                        </ul>
                    </div>
                    <div class="clear"></div>
                    <div id="player1" class="player">
                        <div class="username" id="username_1">
                            <div class="button nolink">
                                #{gameBean.players[0].username}
                            </div>
                        </div>
                        <ul class="cards">
                            <c:forEach var="card" items="#{gameBean.players[0].handCards}">
                                <h:commandLink id="#{card.color}_#{card.rank}">
                                    <li class="card left radius #{fn:toLowerCase(card.color)}_#{fn:toLowerCase(card.rank)}">
                                       <!-- #{card.color}_#{card.rank} -->
                                        <f:ajax event="click" render="@form" execute="@this" listener="#{gameBean.cardClickListener}"/>
                                    </li>
                                </h:commandLink>
                            </c:forEach>
                        </ul>
                    </div>
                    <t:div rendered="#{gameBean.hasWinner}">
                        <script type="text/javascript">
                            stopAjaxPoll();
                        </script>
                    </t:div>
                </t:div>
            </div>
            <t:div id="teamPoints">
                <div id="totalPoints">
                    (#{gameBean.players[0].username} &amp; #{gameBean.players[2].username})
                    <span>#{gameBean.totalTeamPoints[0]} #{text.points}</span>
                    :
                    <span>#{gameBean.totalTeamPoints[1]} #{text.points}</span>
                    (#{gameBean.players[1].username} &amp; #{gameBean.players[3].username}) 
                </div>
            </t:div>
            <div id="leave">
                <h:commandButton id="leaveBtn" action="#{gameBean.leave}" value="#{text.gameLeaveButton}" class="button red small"/>
            </div>
        </ui:composition>
    </h:body>
</html>

web/gameoverview.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"     
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
    </h:head>
    <h:body>
        <ui:composition>            
            <h2 id="overview_title">#{text.overview}</h2>
            <div id="game_overview" class="radius">
                <h:commandButton id="newGameBtn" action="#{gameBean.newGame}" value="#{text.gameNewButton}" class="button green"/>
                <h:dataTable id="gameoverview" value="#{gameBean.gameOverview}" var="game">
                    <h:column>
                        <f:facet name="header">#{text.gameGame}</f:facet>
                        <h:outputText value="#{game.gameID}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">#{text.gamePlayers}</f:facet>
                        <h:outputText value="#{game.playerCount} / #{game.maxPlayerCount}"/>
                    </h:column>
                    <h:column>
                        <h:commandLink id="joinBtn" action="game" actionListener="#{gameBean.join}" title="#{game.gameID}" value="#{text.gameJoinButton}" class="button small green" />
                    </h:column>
                </h:dataTable>
            </div>
        </ui:composition>
    </h:body>
</html>

web/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:t="http://myfaces.apache.org/tomahawk"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <f:view contentType="text/html" locale="#{mainBean.locale}"/>
    <h:head>
        <title>#{text.mainTitle}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <script type="text/javascript" src="script/jquery-1.7.1.min.js" />
        <script type="text/javascript" src="script/jass.js" />
        <link rel="stylesheet" type="text/css" media="all" href="css/styles.css" />
        <link href='http://fonts.googleapis.com/css?family=Engagement|Vibur|Duru+Sans' rel='stylesheet' type='text/css'/>
    </h:head>
    <h:body>
        <t:div rendered="#{mainBean.hasUser}">
            <div id="profile">
                <div id="profileContent">
                    <h2>
                        #{mainBean.user.username}
                    </h2>
                    <div id="stats">
                        <table>
                            <thead>
                                <tr>
                                    <td class="team">#{text.yourTeam}</td>
                                    <td class="points"></td>
                                    <td class="middle"></td>
                                    <td class="team">#{text.opponentTeam}</td>
                                    <td class="points"></td>
                                    <td></td>
                                </tr>
                            </thead>
                            <tbody>
                                <c:forEach var="game" items="#{mainBean.gameHistory}">
                                    <tr>
                                        <td>#{game.teams[0].teamPlayers}</td>
                                        <td align="right">#{game.teams[0].teamPoints} #{text.points}</td>
                                        <td></td>
                                        <td>#{game.teams[1].teamPlayers}</td>
                                        <td align="right">#{game.teams[1].teamPoints} #{text.points}</td>
                                        <c:if test="#{game.hasWon}">
                                            <td class="win">
                                                #{text.win}
                                            </td>
                                        </c:if>
                                        <c:if test="#{not game.hasWon}">
                                            <td class="defeat">
                                                #{text.defeat}
                                            </td>
                                        </c:if>
                                    </tr>
                                </c:forEach>       
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </t:div>
        <t:div rendered="#{mainBean.hasUser}">
            <a id="profilebutton">
                <span>#{text.gameProfile} &amp; Stats</span>
            </a>
        </t:div>
        <h:form id="contentForm">

            <div id="wrapper">
                <ui:insert name="content">Content</ui:insert>
            </div>
        </h:form>
        <div id="locale">
            <h:form>
                <h:commandLink id="fr" value="#{text.french}" >
                    <f:actionListener type="ch.bfh.jass.listener.LanguageChangedActionEvent" />
                </h:commandLink>&nbsp;
                <h:commandLink id="de" value="#{text.german}" >
                    <f:actionListener type="ch.bfh.jass.listener.LanguageChangedActionEvent" />
                </h:commandLink>&nbsp;
                <h:commandLink id="en" value="#{text.english}" >
                    <f:actionListener type="ch.bfh.jass.listener.LanguageChangedActionEvent" />
                </h:commandLink>
            </h:form>
        </div>
    </h:body>
</html>